namespace Gimzo.Infrastructure.Database;

internal static class SqlRepository
{
    public const string FullAuditSelect = @"created_by AS CreatedBy,
updated_by AS UpdatedBy,
created_at_unix_ms AS CreatedAtUnixMs,
updated_at_unix_ms AS UpdatedAtUnixMs";


    public const string InsertStockSymbols = @"
INSERT INTO public.stock_symbols (
    symbol,
    registrant,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @Registrant,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeStockSymbols = @"
INSERT INTO public.stock_symbols (
    symbol,
    registrant,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @Registrant,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (symbol) DO UPDATE SET
    registrant = EXCLUDED.registrant,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectStockSymbols = $@"
SELECT
    symbol,
    registrant,
    {FullAuditSelect}
FROM public.stock_symbols";

    
    public const string InsertEtfSymbols = @"
INSERT INTO public.etf_symbols (
    symbol,
    description,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @Description,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeEtfSymbols = @"
INSERT INTO public.etf_symbols (
    symbol,
    description,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @Description,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (symbol) DO UPDATE SET
    description = EXCLUDED.description,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectEtfSymbols = $@"
SELECT
    symbol,
    description AS Description,
    {FullAuditSelect}
FROM public.etf_symbols";

    
    public const string InsertCommoditySymbols = @"
INSERT INTO public.commodity_symbols (
    symbol,
    description,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @Description,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeCommoditySymbols = @"
INSERT INTO public.commodity_symbols (
    symbol,
    description,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @Description,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (symbol) DO UPDATE SET
    description = EXCLUDED.description,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectCommoditySymbols = $@"
SELECT
    symbol,
    description AS Description,
    {FullAuditSelect}
FROM public.commodity_symbols";

    
    public const string InsertOtcSymbols = @"
INSERT INTO public.otc_symbols (
    symbol,
    title,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @Title,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeOtcSymbols = @"
INSERT INTO public.otc_symbols (
    symbol,
    title,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @Title,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (symbol) DO UPDATE SET
    title = EXCLUDED.title,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectOtcSymbols = $@"
SELECT
    symbol,
    title AS Title,
    {FullAuditSelect}
FROM public.otc_symbols";

    
    public const string InsertCryptoSymbols = @"
INSERT INTO public.crypto_symbols (
    symbol,
    base_asset,
    quote_asset,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @BaseAsset,
    @QuoteAsset,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeCryptoSymbols = @"
INSERT INTO public.crypto_symbols (
    symbol,
    base_asset,
    quote_asset,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @BaseAsset,
    @QuoteAsset,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (symbol) DO UPDATE SET
    base_asset = EXCLUDED.base_asset,
    quote_asset = EXCLUDED.quote_asset,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectCryptoSymbols = $@"
SELECT
    symbol,
    base_asset AS BaseAsset,
    quote_asset AS QuoteAsset,
    {FullAuditSelect}
FROM public.crypto_symbols";

    
    public const string InsertIndexSymbols = @"
INSERT INTO public.index_symbols (
    symbol,
    index_name,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @IndexName,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeIndexSymbols = @"
INSERT INTO public.index_symbols (
    symbol,
    index_name,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @IndexName,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT(symbol) DO UPDATE SET
    index_name = EXCLUDED.index_name,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectIndexSymbols = $@"
SELECT
    symbol,
    index_name AS IndexName,
    {FullAuditSelect}
FROM public.index_symbols";

    
    public const string InsertSecurityInformation = @"
INSERT INTO public.security_information (
    symbol,
    issuer,
    cusip,
    isin,
    figi,
    type,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @Issuer,
    @Cusip,
    @Isin,
    @Figi,
    @Type,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeSecurityInformation = @"
INSERT INTO public.security_information (
    symbol,
    issuer,
    cusip,
    isin,
    figi,
    type,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @Issuer,
    @Cusip,
    @Isin,
    @Figi,
    @Type,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (symbol) DO UPDATE SET
    issuer = EXCLUDED.issuer,
    cusip = EXCLUDED.cusip,
    isin = EXCLUDED.isin,
    figi = EXCLUDED.figi,
    type = EXCLUDED.type,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectSecurityInformation = $@"
SELECT
    symbol,
    issuer,
    cusip,
    isin,
    figi,
    type,
    {FullAuditSelect}
FROM public.security_information";

    
    public const string InsertEodPrices = @"
INSERT INTO public.eod_prices (
    symbol,
    date_eod,
    open,
    high,
    low,
    close,
    volume,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @Date,
    @Open,
    @High,
    @Low,
    @Close,
    @Volume,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeEodPrices = @"
INSERT INTO public.eod_prices (
    symbol,
    date_eod,
    open,
    high,
    low,
    close,
    volume,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @Date,
    @Open,
    @High,
    @Low,
    @Close,
    @Volume,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (symbol, date_eod) DO UPDATE SET
    open = EXCLUDED.open,
    high = EXCLUDED.high,
    low = EXCLUDED.low,
    close = EXCLUDED.close,
    volume = EXCLUDED.volume,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectEodPrices = $@"
SELECT
    symbol,
    date_eod AS Date,
    open AS Open,
    high AS High,
    low AS Low,
    close AS Close,
    volume AS Volume,
    {FullAuditSelect}
FROM public.eod_prices";

    
    public const string InsertCompanyInfo = @"
INSERT INTO public.us_companies (
    central_index_key,
    exchange,
    symbol,
    registrant,
    isin,
    lei,
    ein,
    sic_code,
    sic_description,
    sic_title,
    fiscal_year_end,
    state_of_incorporation,
    phone_number,
    mailing_address,
    business_address,
    former_name,
    industry,
    date_founding,
    chief_executive_officer,
    number_employees,
    web_site,
    market_cap,
    shares_issued,
    shares_outstanding,
    description,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @CentralIndexKey,
    @Exchange,
    @Symbol,
    @Registrant,
    @Isin,
    @Lei,
    @Ein,
    @SicCode,
    @SicDescription,
    @SicTitle,
    @FiscalYearEnd,
    @StateOfIncorporation,
    @PhoneNumber,
    @MailingAddress,
    @BusinessAddress,
    @FormerName,
    @Industry,
    @DateFounding,
    @ChiefExecutiveOfficer,
    @NumberEmployees,
    @WebSite,
    @MarketCap,
    @SharesIssued,
    @SharesOutstanding,
    @Description,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeCompanyInfo = @"
INSERT INTO public.us_companies (
    central_index_key,
    exchange,
    symbol,
    registrant,
    isin,
    lei,
    ein,
    sic_code,
    sic_description,
    sic_title,
    fiscal_year_end,
    state_of_incorporation,
    phone_number,
    mailing_address,
    business_address,
    former_name,
    industry,
    date_founding,
    chief_executive_officer,
    number_employees,
    web_site,
    market_cap,
    shares_issued,
    shares_outstanding,
    description,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @CentralIndexKey,
    @Exchange,
    @Symbol,
    @Registrant,
    @Isin,
    @Lei,
    @Ein,
    @SicCode,
    @SicDescription,
    @SicTitle,
    @FiscalYearEnd,
    @StateOfIncorporation,
    @PhoneNumber,
    @MailingAddress,
    @BusinessAddress,
    @FormerName,
    @Industry,
    @DateFounding,
    @ChiefExecutiveOfficer,
    @NumberEmployees,
    @WebSite,
    @MarketCap,
    @SharesIssued,
    @SharesOutstanding,
    @Description,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (central_index_key, exchange, symbol) DO UPDATE SET
    registrant = EXCLUDED.registrant,
    isin = EXCLUDED.isin,
    lei = EXCLUDED.lei,
    ein = EXCLUDED.ein,
    sic_code = EXCLUDED.sic_code,
    sic_description = EXCLUDED.sic_description,
    sic_title = EXCLUDED.sic_title,
    fiscal_year_end = EXCLUDED.fiscal_year_end,
    state_of_incorporation = EXCLUDED.state_of_incorporation,
    phone_number = EXCLUDED.phone_number,
    mailing_address = EXCLUDED.mailing_address,
    business_address = EXCLUDED.business_address,
    former_name = EXCLUDED.former_name,
    industry = EXCLUDED.industry,
    date_founding = EXCLUDED.date_founding,
    chief_executive_officer = EXCLUDED.chief_executive_officer,
    number_employees = EXCLUDED.number_employees,
    web_site = EXCLUDED.web_site,
    market_cap = EXCLUDED.market_cap,
    shares_issued = EXCLUDED.shares_issued,
    shares_outstanding = EXCLUDED.shares_outstanding,
    description = EXCLUDED.description,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectCompanyInfo = $@"
SELECT
    central_index_key AS CentralIndexKey,
    exchange AS Exchange,
    symbol AS Symbol,
    registrant AS Registrant,
    isin AS Isin,
    lei AS Lei,
    ein AS Ein,
    sic_code AS SicCode,
    sic_description AS SicDescription,
    sic_title as SicTitle,
    fiscal_year_end AS FiscalYearEnd,
    state_of_incorporation AS StateOfIncorporation,
    phone_number AS PhoneNumber,
    mailing_address AS MailingAddress,
    business_address AS BusinessAddress,
    former_name AS FormerName,
    industry AS Industry,
    date_founding AS DateFounding,
    chief_executive_officer AS ChiefExecutiveOfficer,
    number_employees AS NumberEmployees,
    web_site AS WebSite,
    market_cap AS MarketCap,
    shares_issued AS SharesIssued,
    shares_outstanding AS SharesOutstanding,
    description AS Description,
    {FullAuditSelect}
FROM public.us_companies";

    
    public const string InsertLiquidityRatios = @"
INSERT INTO public.liquidity_ratios (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    fiscal_period,
    period_end_date,
    working_capital,
    current_ratio,
    cash_ratio,
    quick_ratio,
    days_of_inventory_outstanding,
    days_of_sales_outstanding,
    days_payable_outstanding,
    cash_conversion_cycle,
    sales_to_working_capital_ratio,
    cash_to_current_liabilities_ratio,
    working_capital_to_debt_ratio,
    cash_flow_adequacy_ratio,
    sales_to_current_assets_ratio,
    cash_to_current_assets_ratio,
    cash_to_working_capital_ratio,
    inventory_to_working_capital_ratio,
    net_debt,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @FiscalPeriod,
    @PeriodEndDate,
    @WorkingCapital,
    @CurrentRatio,
    @CashRatio,
    @QuickRatio,
    @DaysOfInventoryOutstanding,
    @DaysOfSalesOutstanding,
    @DaysPayableOutstanding,
    @CashConversionCycle,
    @SalesToWorkingCapitalRatio,
    @CashToCurrentLiabilitiesRatio,
    @WorkingCapitalToDebtRatio,
    @CashFlowAdequacyRatio,
    @SalesToCurrentAssetsRatio,
    @CashToCurrentAssetsRatio,
    @CashToWorkingCapitalRatio,
    @InventoryToWorkingCapitalRatio,
    @NetDebt,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeLiquidityRatios = @"
INSERT INTO public.liquidity_ratios (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    fiscal_period,
    period_end_date,
    working_capital,
    current_ratio,
    cash_ratio,
    quick_ratio,
    days_of_inventory_outstanding,
    days_of_sales_outstanding,
    days_payable_outstanding,
    cash_conversion_cycle,
    sales_to_working_capital_ratio,
    cash_to_current_liabilities_ratio,
    working_capital_to_debt_ratio,
    cash_flow_adequacy_ratio,
    sales_to_current_assets_ratio,
    cash_to_current_assets_ratio,
    cash_to_working_capital_ratio,
    inventory_to_working_capital_ratio,
    net_debt,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @FiscalPeriod,
    @PeriodEndDate,
    @WorkingCapital,
    @CurrentRatio,
    @CashRatio,
    @QuickRatio,
    @DaysOfInventoryOutstanding,
    @DaysOfSalesOutstanding,
    @DaysPayableOutstanding,
    @CashConversionCycle,
    @SalesToWorkingCapitalRatio,
    @CashToCurrentLiabilitiesRatio,
    @WorkingCapitalToDebtRatio,
    @CashFlowAdequacyRatio,
    @SalesToCurrentAssetsRatio,
    @CashToCurrentAssetsRatio,
    @CashToWorkingCapitalRatio,
    @InventoryToWorkingCapitalRatio,
    @NetDebt,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (central_index_key, fiscal_year, fiscal_period) DO UPDATE SET
    symbol = EXCLUDED.symbol,
    registrant = EXCLUDED.registrant,
    period_end_date = EXCLUDED.period_end_date,
    working_capital = EXCLUDED.working_capital,
    current_ratio = EXCLUDED.current_ratio,
    cash_ratio = EXCLUDED.cash_ratio,
    quick_ratio = EXCLUDED.quick_ratio,
    days_of_inventory_outstanding = EXCLUDED.days_of_inventory_outstanding,
    days_of_sales_outstanding = EXCLUDED.days_of_sales_outstanding,
    days_payable_outstanding = EXCLUDED.days_payable_outstanding,
    cash_conversion_cycle = EXCLUDED.cash_conversion_cycle,
    sales_to_working_capital_ratio = EXCLUDED.sales_to_working_capital_ratio,
    cash_to_current_liabilities_ratio = EXCLUDED.cash_to_current_liabilities_ratio,
    working_capital_to_debt_ratio = EXCLUDED.working_capital_to_debt_ratio,
    cash_flow_adequacy_ratio = EXCLUDED.cash_flow_adequacy_ratio,
    sales_to_current_assets_ratio = EXCLUDED.sales_to_current_assets_ratio,
    cash_to_current_assets_ratio = EXCLUDED.cash_to_current_assets_ratio,
    cash_to_working_capital_ratio = EXCLUDED.cash_to_working_capital_ratio,
    inventory_to_working_capital_ratio = EXCLUDED.inventory_to_working_capital_ratio,
    net_debt = EXCLUDED.net_debt,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectLiquidityRatios = $@"
SELECT
    symbol,
    central_index_key AS CentralIndexKey,
    registrant,
    fiscal_year AS FiscalYear,
    fiscal_period AS FiscalPeriod,
    period_end_date AS PeriodEndDate,
    working_capital AS WorkingCapital,
    current_ratio AS CurrentRatio,
    cash_ratio AS CashRatio,
    quick_ratio AS QuickRatio,
    days_of_inventory_outstanding AS DaysOfInventoryOutstanding,
    days_of_sales_outstanding AS DaysOfSalesOutstanding,
    days_payable_outstanding AS DaysPayableOutstanding,
    cash_conversion_cycle AS CashConversionCycle,
    sales_to_working_capital_ratio AS SalesToWorkingCapitalRatio,
    cash_to_current_liabilities_ratio AS CashToCurrentLiabilitiesRatio,
    working_capital_to_debt_ratio AS WorkingCapitalToDebtRatio,
    cash_flow_adequacy_ratio AS CashFlowAdequacyRatio,
    sales_to_current_assets_ratio AS SalesToCurrentAssetsRatio,
    cash_to_current_assets_ratio AS CashToCurrentAssetsRatio,
    cash_to_working_capital_ratio AS CashToWorkingCapitalRatio,
    inventory_to_working_capital_ratio AS InventoryToWorkingCapitalRatio,
    net_debt AS NetDebt,
    {FullAuditSelect}
FROM public.liquidity_ratios";

    
    public const string InsertProfitabilityRatios = @"
INSERT INTO public.profitability_ratios (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    fiscal_period,
    period_end_date,
    ebit,
    ebitda,
    profit_margin,
    gross_margin,
    operating_margin,
    operating_cash_flow_margin,
    return_on_equity,
    return_on_assets,
    return_on_debt,
    cash_return_on_assets,
    cash_turnover_ratio,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @FiscalPeriod,
    @PeriodEndDate,
    @Ebit,
    @Ebitda,
    @ProfitMargin,
    @GrossMargin,
    @OperatingMargin,
    @OperatingCashFlowMargin,
    @ReturnOnEquity,
    @ReturnOnAssets,
    @ReturnOnDebt,
    @CashReturnOnAssets,
    @CashTurnoverRatio,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeProfitabilityRatios = @"
INSERT INTO public.profitability_ratios (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    fiscal_period,
    period_end_date,
    ebit,
    ebitda,
    profit_margin,
    gross_margin,
    operating_margin,
    operating_cash_flow_margin,
    return_on_equity,
    return_on_assets,
    return_on_debt,
    cash_return_on_assets,
    cash_turnover_ratio,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @FiscalPeriod,
    @PeriodEndDate,
    @Ebit,
    @Ebitda,
    @ProfitMargin,
    @GrossMargin,
    @OperatingMargin,
    @OperatingCashFlowMargin,
    @ReturnOnEquity,
    @ReturnOnAssets,
    @ReturnOnDebt,
    @CashReturnOnAssets,
    @CashTurnoverRatio,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (central_index_key, fiscal_year, fiscal_period) DO UPDATE SET
    symbol = EXCLUDED.symbol,
    registrant = EXCLUDED.registrant,
    period_end_date = EXCLUDED.period_end_date,
    ebit = EXCLUDED.ebit,
    ebitda = EXCLUDED.ebitda,
    profit_margin = EXCLUDED.profit_margin,
    gross_margin = EXCLUDED.gross_margin,
    operating_margin = EXCLUDED.operating_margin,
    operating_cash_flow_margin = EXCLUDED.operating_cash_flow_margin,
    return_on_equity = EXCLUDED.return_on_equity,
    return_on_assets = EXCLUDED.return_on_assets,
    return_on_debt = EXCLUDED.return_on_debt,
    cash_return_on_assets = EXCLUDED.cash_return_on_assets,
    cash_turnover_ratio = EXCLUDED.cash_turnover_ratio,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectProfitabilityRatios = $@"
SELECT
    symbol,
    central_index_key AS CentralIndexKey,
    registrant,
    fiscal_year AS FiscalYear,
    fiscal_period AS FiscalPeriod,
    period_end_date AS PeriodEndDate,
    ebit AS Ebit,
    ebitda AS Ebitda,
    profit_margin AS ProfitMargin,
    gross_margin AS GrossMargin,
    operating_margin AS OperatingMargin,
    operating_cash_flow_margin AS OperatingCashFlowMargin,
    return_on_equity AS ReturnOnEquity,
    return_on_assets AS ReturnOnAssets,
    return_on_debt AS ReturnOnDebt,
    cash_return_on_assets AS CashReturnOnAssets,
    cash_turnover_ratio AS CashTurnoverRatio,
    {FullAuditSelect}
FROM public.profitability_ratios";

    
    public const string InsertSolvencyRatios = @"
INSERT INTO public.solvency_ratios (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    fiscal_period,
    period_end_date,
    equity_ratio,
    debt_coverage_ratio,
    asset_coverage_ratio,
    interest_coverage_ratio,
    debt_to_equity_ratio,
    debt_to_assets_ratio,
    debt_to_capital_ratio,
    debt_to_income_ratio,
    cash_flow_to_debt_ratio,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @FiscalPeriod,
    @PeriodEndDate,
    @EquityRatio,
    @DebtCoverageRatio,
    @AssetCoverageRatio,
    @InterestCoverageRatio,
    @DebtToEquityRatio,
    @DebtToAssetsRatio,
    @DebtToCapitalRatio,
    @DebtToIncomeRatio,
    @CashFlowToDebtRatio,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeSolvencyRatios = @"
INSERT INTO public.solvency_ratios (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    fiscal_period,
    period_end_date,
    equity_ratio,
    debt_coverage_ratio,
    asset_coverage_ratio,
    interest_coverage_ratio,
    debt_to_equity_ratio,
    debt_to_assets_ratio,
    debt_to_capital_ratio,
    debt_to_income_ratio,
    cash_flow_to_debt_ratio,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @FiscalPeriod,
    @PeriodEndDate,
    @EquityRatio,
    @DebtCoverageRatio,
    @AssetCoverageRatio,
    @InterestCoverageRatio,
    @DebtToEquityRatio,
    @DebtToAssetsRatio,
    @DebtToCapitalRatio,
    @DebtToIncomeRatio,
    @CashFlowToDebtRatio,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (central_index_key, fiscal_year, fiscal_period) DO UPDATE SET
    symbol = EXCLUDED.symbol,
    registrant = EXCLUDED.registrant,
    period_end_date = EXCLUDED.period_end_date,
    equity_ratio = EXCLUDED.equity_ratio,
    debt_coverage_ratio = EXCLUDED.debt_coverage_ratio,
    asset_coverage_ratio = EXCLUDED.asset_coverage_ratio,
    interest_coverage_ratio = EXCLUDED.interest_coverage_ratio,
    debt_to_equity_ratio = EXCLUDED.debt_to_equity_ratio,
    debt_to_assets_ratio = EXCLUDED.debt_to_assets_ratio,
    debt_to_capital_ratio = EXCLUDED.debt_to_capital_ratio,
    debt_to_income_ratio = EXCLUDED.debt_to_income_ratio,
    cash_flow_to_debt_ratio = EXCLUDED.cash_flow_to_debt_ratio,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectSolvencyRatios = $@"
SELECT
    symbol,
    central_index_key AS CentralIndexKey,
    registrant,
    fiscal_year AS FiscalYear,
    fiscal_period AS FiscalPeriod,
    period_end_date AS PeriodEndDate,
    equity_ratio AS EquityRatio,
    debt_coverage_ratio AS DebtCoverageRatio,
    asset_coverage_ratio AS AssetCoverageRatio,
    interest_coverage_ratio AS InterestCoverageRatio,
    debt_to_equity_ratio AS DebtToEquityRatio,
    debt_to_assets_ratio AS DebtToAssetsRatio,
    debt_to_capital_ratio AS DebtToCapitalRatio,
    debt_to_income_ratio AS DebtToIncomeRatio,
    cash_flow_to_debt_ratio AS CashFlowToDebtRatio,
    {FullAuditSelect}
FROM public.solvency_ratios";

    
    public const string InsertValuationRatios = @"
INSERT INTO public.valuation_ratios (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    fiscal_period,
    period_end_date,
    dividends_per_share,
    dividend_payout_ratio,
    book_value_per_share,
    retention_ratio,
    net_fixed_assets,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @FiscalPeriod,
    @PeriodEndDate,
    @DividendsPerShare,
    @DividendPayoutRatio,
    @BookValuePerShare,
    @RetentionRatio,
    @NetFixedAssets,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeValuationRatios = @"
INSERT INTO public.valuation_ratios (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    fiscal_period,
    period_end_date,
    dividends_per_share,
    dividend_payout_ratio,
    book_value_per_share,
    retention_ratio,
    net_fixed_assets,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @FiscalPeriod,
    @PeriodEndDate,
    @DividendsPerShare,
    @DividendPayoutRatio,
    @BookValuePerShare,
    @RetentionRatio,
    @NetFixedAssets,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (central_index_key, fiscal_year, fiscal_period) DO UPDATE SET
    symbol = EXCLUDED.symbol,
    registrant = EXCLUDED.registrant,
    period_end_date = EXCLUDED.period_end_date,
    dividends_per_share = EXCLUDED.dividends_per_share,
    dividend_payout_ratio = EXCLUDED.dividend_payout_ratio,
    book_value_per_share = EXCLUDED.book_value_per_share,
    retention_ratio = EXCLUDED.retention_ratio,
    net_fixed_assets = EXCLUDED.net_fixed_assets,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectValuationRatios = $@"
SELECT
    symbol,
    central_index_key AS CentralIndexKey,
    registrant,
    fiscal_year AS FiscalYear,
    fiscal_period AS FiscalPeriod,
    period_end_date AS PeriodEndDate,
    dividends_per_share AS DividendsPerShare,
    dividend_payout_ratio AS DividendPayoutRatio,
    book_value_per_share AS BookValuePerShare,
    retention_ratio AS RetentionRatio,
    net_fixed_assets AS NetFixedAssets,
    {FullAuditSelect}
FROM public.valuation_ratios";

    
    public const string InsertKeyMetrics = @"
INSERT INTO public.key_metrics (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    period_end_date,
    earnings_per_share,
    earnings_per_share_forecast,
    price_to_earnings_ratio,
    forward_price_to_earnings_ratio,
    earnings_growth_rate,
    price_earnings_to_growth_rate,
    book_value_per_share,
    price_to_book_ratio,
    ebitda,
    enterprise_value,
    dividend_yield,
    dividend_payout_ratio,
    debt_to_equity_ratio,
    capital_expenditures,
    free_cash_flow,
    return_on_equity,
    one_year_beta,
    three_year_beta,
    five_year_beta,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @PeriodEndDate,
    @EarningsPerShare,
    @EarningsPerShareForecast,
    @PriceToEarningsRatio,
    @ForwardPriceToEarningsRatio,
    @EarningsGrowthRate,
    @PriceEarningsToGrowthRate,
    @BookValuePerShare,
    @PriceToBookRatio,
    @Ebitda,
    @EnterpriseValue,
    @DividendYield,
    @DividendPayoutRatio,
    @DebtToEquityRatio,
    @CapitalExpenditures,
    @FreeCashFlow,
    @ReturnOnEquity,
    @OneYearBeta,
    @ThreeYearBeta,
    @FiveYearBeta,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeKeyMetrics = @"
INSERT INTO public.key_metrics (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    period_end_date,
    earnings_per_share,
    earnings_per_share_forecast,
    price_to_earnings_ratio,
    forward_price_to_earnings_ratio,
    earnings_growth_rate,
    price_earnings_to_growth_rate,
    book_value_per_share,
    price_to_book_ratio,
    ebitda,
    enterprise_value,
    dividend_yield,
    dividend_payout_ratio,
    debt_to_equity_ratio,
    capital_expenditures,
    free_cash_flow,
    return_on_equity,
    one_year_beta,
    three_year_beta,
    five_year_beta,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @PeriodEndDate,
    @EarningsPerShare,
    @EarningsPerShareForecast,
    @PriceToEarningsRatio,
    @ForwardPriceToEarningsRatio,
    @EarningsGrowthRate,
    @PriceEarningsToGrowthRate,
    @BookValuePerShare,
    @PriceToBookRatio,
    @Ebitda,
    @EnterpriseValue,
    @DividendYield,
    @DividendPayoutRatio,
    @DebtToEquityRatio,
    @CapitalExpenditures,
    @FreeCashFlow,
    @ReturnOnEquity,
    @OneYearBeta,
    @ThreeYearBeta,
    @FiveYearBeta,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (central_index_key, fiscal_year) DO UPDATE SET
    symbol = EXCLUDED.symbol,
    registrant = EXCLUDED.registrant,
    period_end_date = EXCLUDED.period_end_date,
    earnings_per_share = EXCLUDED.earnings_per_share,
    earnings_per_share_forecast = EXCLUDED.earnings_per_share_forecast,
    price_to_earnings_ratio = EXCLUDED.price_to_earnings_ratio,
    forward_price_to_earnings_ratio = EXCLUDED.forward_price_to_earnings_ratio,
    earnings_growth_rate = EXCLUDED.earnings_growth_rate,
    price_earnings_to_growth_rate = EXCLUDED.price_earnings_to_growth_rate,
    book_value_per_share = EXCLUDED.book_value_per_share,
    price_to_book_ratio = EXCLUDED.price_to_book_ratio,
    ebitda = EXCLUDED.ebitda,
    enterprise_value = EXCLUDED.enterprise_value,
    dividend_yield = EXCLUDED.dividend_yield,
    dividend_payout_ratio = EXCLUDED.dividend_payout_ratio,
    debt_to_equity_ratio = EXCLUDED.debt_to_equity_ratio,
    capital_expenditures = EXCLUDED.capital_expenditures,
    free_cash_flow = EXCLUDED.free_cash_flow,
    return_on_equity = EXCLUDED.return_on_equity,
    one_year_beta = EXCLUDED.one_year_beta,
    three_year_beta = EXCLUDED.three_year_beta,
    five_year_beta = EXCLUDED.five_year_beta,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectKeyMetrics = $@"
SELECT
    symbol,
    central_index_key AS CentralIndexKey,
    registrant,
    fiscal_year AS FiscalYear,
    period_end_date AS PeriodEndDate,
    earnings_per_share AS EarningsPerShare,
    earnings_per_share_forecast AS EarningsPerShareForecast,
    price_to_earnings_ratio AS PriceToEarningsRatio,
    forward_price_to_earnings_ratio AS ForwardPriceToEarningsRatio,
    earnings_growth_rate AS EarningsGrowthRate,
    price_earnings_to_growth_rate AS PriceEarningsToGrowthRate,
    book_value_per_share AS BookValuePerShare,
    price_to_book_ratio AS PriceToBookRatio,
    ebitda AS Ebitda,
    enterprise_value AS EnterpriseValue,
    dividend_yield AS DividendYield,
    dividend_payout_ratio AS DividendPayoutRatio,
    debt_to_equity_ratio AS DebtToEquityRatio,
    capital_expenditures AS CapitalExpenditures,
    free_cash_flow AS FreeCashFlow,
    return_on_equity AS ReturnOnEquity,
    one_year_beta AS OneYearBeta,
    three_year_beta AS ThreeYearBeta,
    five_year_beta AS FiveYearBeta,
    {FullAuditSelect}
FROM public.key_metrics";

    
    public const string InsertMarketCaps = @"
INSERT INTO public.market_caps (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    value,
    change_in_market_cap,
    percentage_change_in_market_cap,
    shares_outstanding,
    change_in_shares_outstanding,
    percentage_change_in_shares_outstanding,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @Value,
    @ChangeInMarketCap,
    @PercentageChangeInMarketCap,
    @SharesOutstanding,
    @ChangeInSharesOutstanding,
    @PercentageChangeInSharesOutstanding,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeMarketCaps = @"
INSERT INTO public.market_caps (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    value,
    change_in_market_cap,
    percentage_change_in_market_cap,
    shares_outstanding,
    change_in_shares_outstanding,
    percentage_change_in_shares_outstanding,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @Value,
    @ChangeInMarketCap,
    @PercentageChangeInMarketCap,
    @SharesOutstanding,
    @ChangeInSharesOutstanding,
    @PercentageChangeInSharesOutstanding,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (central_index_key, fiscal_year) DO UPDATE SET
    symbol = EXCLUDED.symbol,
    registrant = EXCLUDED.registrant,
    value = EXCLUDED.value,
    change_in_market_cap = EXCLUDED.change_in_market_cap,
    percentage_change_in_market_cap = EXCLUDED.percentage_change_in_market_cap,
    shares_outstanding = EXCLUDED.shares_outstanding,
    change_in_shares_outstanding = EXCLUDED.change_in_shares_outstanding,
    percentage_change_in_shares_outstanding = EXCLUDED.percentage_change_in_shares_outstanding,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectMarketCaps = $@"
SELECT
    symbol,
    central_index_key AS CentralIndexKey,
    registrant,
    fiscal_year AS FiscalYear,
    value AS Value,
    change_in_market_cap AS ChangeInMarketCap,
    percentage_change_in_market_cap AS PercentageChangeInMarketCap,
    shares_outstanding AS SharesOutstanding,
    change_in_shares_outstanding AS ChangeInSharesOutstanding,
    percentage_change_in_shares_outstanding AS PercentageChangeInSharesOutstanding,
    {FullAuditSelect}
FROM public.market_caps";

    
    public const string InsertEmployeeCounts = @"
INSERT INTO public.employee_counts (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    count,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @Count,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeEmployeeCounts = @"
INSERT INTO public.employee_counts (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    count,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @Count,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (central_index_key, fiscal_year) DO UPDATE SET
    symbol = EXCLUDED.symbol,
    registrant = EXCLUDED.registrant,
    count = EXCLUDED.count,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectEmployeeCounts = $@"
SELECT
    symbol,
    central_index_key AS CentralIndexKey,
    registrant,
    fiscal_year AS FiscalYear,
    count AS Count,
    {FullAuditSelect}
FROM public.employee_counts";

    
    public const string InsertExecutiveCompensations = @"
INSERT INTO public.executive_compensations (
    symbol,
    central_index_key,
    registrant,
    name,
    position,
    fiscal_year,
    salary,
    bonus,
    stock_awards,
    incentive_plan_compensation,
    other_compensation,
    total_compensation,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @Name,
    @Position,
    @FiscalYear,
    @Salary,
    @Bonus,
    @StockAwards,
    @IncentivePlanCompensation,
    @OtherCompensation,
    @TotalCompensation,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeExecutiveCompensations = @"
INSERT INTO public.executive_compensations (
    symbol,
    central_index_key,
    registrant,
    name,
    position,
    fiscal_year,
    salary,
    bonus,
    stock_awards,
    incentive_plan_compensation,
    other_compensation,
    total_compensation,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @Name,
    @Position,
    @FiscalYear,
    @Salary,
    @Bonus,
    @StockAwards,
    @IncentivePlanCompensation,
    @OtherCompensation,
    @TotalCompensation,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (central_index_key, name, position, fiscal_year) DO UPDATE SET
    symbol = EXCLUDED.symbol,
    registrant = EXCLUDED.registrant,
    salary = EXCLUDED.salary,
    bonus = EXCLUDED.bonus,
    stock_awards = EXCLUDED.stock_awards,
    incentive_plan_compensation = EXCLUDED.incentive_plan_compensation,
    other_compensation = EXCLUDED.other_compensation,
    total_compensation = EXCLUDED.total_compensation,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectExecutiveCompensations = $@"
SELECT
    symbol,
    central_index_key AS CentralIndexKey,
    registrant,
    name AS Name,
    position AS Position,
    fiscal_year AS FiscalYear,
    salary AS Salary,
    bonus AS Bonus,
    stock_awards AS StockAwards,
    incentive_plan_compensation AS IncentivePlanCompensation,
    other_compensation AS OtherCompensation,
    total_compensation AS TotalCompensation,
    {FullAuditSelect}
FROM public.executive_compensations";

    
    public const string InsertIncomeStatements = @"
INSERT INTO public.income_statements (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    fiscal_period,
    period_end_date,
    revenue,
    cost_of_revenue,
    gross_profit,
    research_development_expenses,
    general_admin_expenses,
    operating_expenses,
    operating_income,
    interest_expense,
    interest_income,
    net_income,
    earnings_per_share_basic,
    earnings_per_share_diluted,
    weighted_average_shares_outstanding_basic,
    weighted_average_shares_outstanding_diluted,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @FiscalPeriod,
    @PeriodEndDate,
    @Revenue,
    @CostOfRevenue,
    @GrossProfit,
    @ResearchDevelopmentExpenses,
    @GeneralAdminExpenses,
    @OperatingExpenses,
    @OperatingIncome,
    @InterestExpense,
    @InterestIncome,
    @NetIncome,
    @EarningsPerShareBasic,
    @EarningsPerShareDiluted,
    @WeightedAverageSharesOutstandingBasic,
    @WeightedAverageSharesOutstandingDiluted,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeIncomeStatements = @"
INSERT INTO public.income_statements (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    fiscal_period,
    period_end_date,
    revenue,
    cost_of_revenue,
    gross_profit,
    research_development_expenses,
    general_admin_expenses,
    operating_expenses,
    operating_income,
    interest_expense,
    interest_income,
    net_income,
    earnings_per_share_basic,
    earnings_per_share_diluted,
    weighted_average_shares_outstanding_basic,
    weighted_average_shares_outstanding_diluted,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @FiscalPeriod,
    @PeriodEndDate,
    @Revenue,
    @CostOfRevenue,
    @GrossProfit,
    @ResearchDevelopmentExpenses,
    @GeneralAdminExpenses,
    @OperatingExpenses,
    @OperatingIncome,
    @InterestExpense,
    @InterestIncome,
    @NetIncome,
    @EarningsPerShareBasic,
    @EarningsPerShareDiluted,
    @WeightedAverageSharesOutstandingBasic,
    @WeightedAverageSharesOutstandingDiluted,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (central_index_key, fiscal_year, fiscal_period) DO UPDATE SET
    symbol = EXCLUDED.symbol,
    registrant = EXCLUDED.registrant,
    period_end_date = EXCLUDED.period_end_date,
    revenue = EXCLUDED.revenue,
    cost_of_revenue = EXCLUDED.cost_of_revenue,
    gross_profit = EXCLUDED.gross_profit,
    research_development_expenses = EXCLUDED.research_development_expenses,
    general_admin_expenses = EXCLUDED.general_admin_expenses,
    operating_expenses = EXCLUDED.operating_expenses,
    operating_income = EXCLUDED.operating_income,
    interest_expense = EXCLUDED.interest_expense,
    interest_income = EXCLUDED.interest_income,
    net_income = EXCLUDED.net_income,
    earnings_per_share_basic = EXCLUDED.earnings_per_share_basic,
    earnings_per_share_diluted = EXCLUDED.earnings_per_share_diluted,
    weighted_average_shares_outstanding_basic = EXCLUDED.weighted_average_shares_outstanding_basic,
    weighted_average_shares_outstanding_diluted = EXCLUDED.weighted_average_shares_outstanding_diluted,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectIncomeStatements = $@"
SELECT
    symbol,
    central_index_key AS CentralIndexKey,
    registrant,
    fiscal_year AS FiscalYear,
    fiscal_period AS FiscalPeriod,
    period_end_date AS PeriodEndDate,
    revenue AS Revenue,
    cost_of_revenue AS CostOfRevenue,
    gross_profit AS GrossProfit,
    research_development_expenses AS ResearchDevelopmentExpenses,
    general_admin_expenses AS GeneralAdminExpenses,
    operating_expenses AS OperatingExpenses,
    operating_income AS OperatingIncome,
    interest_expense AS InterestExpense,
    interest_income AS InterestIncome,
    net_income AS NetIncome,
    earnings_per_share_basic AS EarningsPerShareBasic,
    earnings_per_share_diluted AS EarningsPerShareDiluted,
    weighted_average_shares_outstanding_basic AS WeightedAverageSharesOutstandingBasic,
    weighted_average_shares_outstanding_diluted AS WeightedAverageSharesOutstandingDiluted,
    {FullAuditSelect}
FROM public.income_statements";

    
    public const string InsertBalanceSheets = @"
INSERT INTO public.balance_sheets (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    fiscal_period,
    period_end_date,
    cash,
    marketable_securities_current,
    accounts_receivable,
    inventories,
    non_trade_receivables,
    other_assets_current,
    total_assets_current,
    marketable_securities_non_current,
    property_plant_equipment,
    other_assets_non_current,
    total_assets_non_current,
    total_assets,
    accounts_payable,
    deferred_revenue,
    short_term_debt,
    other_liabilities_current,
    total_liabilities_current,
    long_term_debt,
    other_liabilities_non_current,
    total_liabilities_non_current,
    total_liabilities,
    common_stock,
    retained_earnings,
    accumulated_other_comprehensive_income,
    total_shareholders_equity,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @FiscalPeriod,
    @PeriodEndDate,
    @Cash,
    @MarketableSecuritiesCurrent,
    @AccountsReceivable,
    @Inventories,
    @NonTradeReceivables,
    @OtherAssetsCurrent,
    @TotalAssetsCurrent,
    @MarketableSecuritiesNonCurrent,
    @PropertyPlantEquipment,
    @OtherAssetsNonCurrent,
    @TotalAssetsNonCurrent,
    @TotalAssets,
    @AccountsPayable,
    @DeferredRevenue,
    @ShortTermDebt,
    @OtherLiabilitiesCurrent,
    @TotalLiabilitiesCurrent,
    @LongTermDebt,
    @OtherLiabilitiesNonCurrent,
    @TotalLiabilitiesNonCurrent,
    @TotalLiabilities,
    @CommonStock,
    @RetainedEarnings,
    @AccumulatedOtherComprehensiveIncome,
    @TotalShareholdersEquity,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeBalanceSheets = @"
INSERT INTO public.balance_sheets (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    fiscal_period,
    period_end_date,
    cash,
    marketable_securities_current,
    accounts_receivable,
    inventories,
    non_trade_receivables,
    other_assets_current,
    total_assets_current,
    marketable_securities_non_current,
    property_plant_equipment,
    other_assets_non_current,
    total_assets_non_current,
    total_assets,
    accounts_payable,
    deferred_revenue,
    short_term_debt,
    other_liabilities_current,
    total_liabilities_current,
    long_term_debt,
    other_liabilities_non_current,
    total_liabilities_non_current,
    total_liabilities,
    common_stock,
    retained_earnings,
    accumulated_other_comprehensive_income,
    total_shareholders_equity,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @FiscalPeriod,
    @PeriodEndDate,
    @Cash,
    @MarketableSecuritiesCurrent,
    @AccountsReceivable,
    @Inventories,
    @NonTradeReceivables,
    @OtherAssetsCurrent,
    @TotalAssetsCurrent,
    @MarketableSecuritiesNonCurrent,
    @PropertyPlantEquipment,
    @OtherAssetsNonCurrent,
    @TotalAssetsNonCurrent,
    @TotalAssets,
    @AccountsPayable,
    @DeferredRevenue,
    @ShortTermDebt,
    @OtherLiabilitiesCurrent,
    @TotalLiabilitiesCurrent,
    @LongTermDebt,
    @OtherLiabilitiesNonCurrent,
    @TotalLiabilitiesNonCurrent,
    @TotalLiabilities,
    @CommonStock,
    @RetainedEarnings,
    @AccumulatedOtherComprehensiveIncome,
    @TotalShareholdersEquity,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (central_index_key, fiscal_year, fiscal_period) DO UPDATE SET
    symbol = EXCLUDED.symbol,
    registrant = EXCLUDED.registrant,
    period_end_date = EXCLUDED.period_end_date,
    cash = EXCLUDED.cash,
    marketable_securities_current = EXCLUDED.marketable_securities_current,
    accounts_receivable = EXCLUDED.accounts_receivable,
    inventories = EXCLUDED.inventories,
    non_trade_receivables = EXCLUDED.non_trade_receivables,
    other_assets_current = EXCLUDED.other_assets_current,
    total_assets_current = EXCLUDED.total_assets_current,
    marketable_securities_non_current = EXCLUDED.marketable_securities_non_current,
    property_plant_equipment = EXCLUDED.property_plant_equipment,
    other_assets_non_current = EXCLUDED.other_assets_non_current,
    total_assets_non_current = EXCLUDED.total_assets_non_current,
    total_assets = EXCLUDED.total_assets,
    accounts_payable = EXCLUDED.accounts_payable,
    deferred_revenue = EXCLUDED.deferred_revenue,
    short_term_debt = EXCLUDED.short_term_debt,
    other_liabilities_current = EXCLUDED.other_liabilities_current,
    total_liabilities_current = EXCLUDED.total_liabilities_current,
    long_term_debt = EXCLUDED.long_term_debt,
    other_liabilities_non_current = EXCLUDED.other_liabilities_non_current,
    total_liabilities_non_current = EXCLUDED.total_liabilities_non_current,
    total_liabilities = EXCLUDED.total_liabilities,
    common_stock = EXCLUDED.common_stock,
    retained_earnings = EXCLUDED.retained_earnings,
    accumulated_other_comprehensive_income = EXCLUDED.accumulated_other_comprehensive_income,
    total_shareholders_equity = EXCLUDED.total_shareholders_equity,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectBalanceSheets = $@"
SELECT
    symbol,
    central_index_key AS CentralIndexKey,
    registrant,
    fiscal_year AS FiscalYear,
    fiscal_period AS FiscalPeriod,
    period_end_date AS PeriodEndDate,
    cash AS Cash,
    marketable_securities_current AS MarketableSecuritiesCurrent,
    accounts_receivable AS AccountsReceivable,
    inventories AS Inventories,
    non_trade_receivables AS NonTradeReceivables,
    other_assets_current AS OtherAssetsCurrent,
    total_assets_current AS TotalAssetsCurrent,
    marketable_securities_non_current AS MarketableSecuritiesNonCurrent,
    property_plant_equipment AS PropertyPlantEquipment,
    other_assets_non_current AS OtherAssetsNonCurrent,
    total_assets_non_current AS TotalAssetsNonCurrent,
    total_assets AS TotalAssets,
    accounts_payable AS AccountsPayable,
    deferred_revenue AS DeferredRevenue,
    short_term_debt AS ShortTermDebt,
    other_liabilities_current AS OtherLiabilitiesCurrent,
    total_liabilities_current AS TotalLiabilitiesCurrent,
    long_term_debt AS LongTermDebt,
    other_liabilities_non_current AS OtherLiabilitiesNonCurrent,
    total_liabilities_non_current AS TotalLiabilitiesNonCurrent,
    total_liabilities AS TotalLiabilities,
    common_stock AS CommonStock,
    retained_earnings AS RetainedEarnings,
    accumulated_other_comprehensive_income AS AccumulatedOtherComprehensiveIncome,
    total_shareholders_equity AS TotalShareholdersEquity,
    {FullAuditSelect}
FROM public.balance_sheets";

    
    public const string InsertCashFlowStatements = @"
INSERT INTO public.cash_flow_statements (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    fiscal_period,
    period_end_date,
    depreciation,
    share_based_compensation_expense,
    deferred_income_tax_expense,
    other_non_cash_income_expense,
    change_in_accounts_receivable,
    change_in_inventories,
    change_in_non_trade_receivables,
    change_in_other_assets,
    change_in_accounts_payable,
    change_in_deferred_revenue,
    change_in_other_liabilities,
    cash_from_operating_activities,
    purchases_of_marketable_securities,
    sales_of_marketable_securities,
    acquisition_of_property,
    acquisition_of_business,
    other_investing_activities,
    cash_from_investing_activities,
    tax_withholding_for_share_based_compensation,
    payments_of_dividends,
    issuance_of_common_stock,
    repurchase_of_common_stock,
    issuance_of_long_term_debt,
    repayment_of_long_term_debt,
    other_financing_activities,
    cash_from_financing_activities,
    change_in_cash,
    cash_at_end_of_period,
    income_taxes_paid,
    interest_paid,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @FiscalPeriod,
    @PeriodEndDate,
    @Depreciation,
    @ShareBasedCompensationExpense,
    @DeferredIncomeTaxExpense,
    @OtherNonCashIncomeExpense,
    @ChangeInAccountsReceivable,
    @ChangeInInventories,
    @ChangeInNonTradeReceivables,
    @ChangeInOtherAssets,
    @ChangeInAccountsPayable,
    @ChangeInDeferredRevenue,
    @ChangeInOtherLiabilities,
    @CashFromOperatingActivities,
    @PurchasesOfMarketableSecurities,
    @SalesOfMarketableSecurities,
    @AcquisitionOfProperty,
    @AcquisitionOfBusiness,
    @OtherInvestingActivities,
    @CashFromInvestingActivities,
    @TaxWithholdingForShareBasedCompensation,
    @PaymentsOfDividends,
    @IssuanceOfCommonStock,
    @RepurchaseOfCommonStock,
    @IssuanceOfLongTermDebt,
    @RepaymentOfLongTermDebt,
    @OtherFinancingActivities,
    @CashFromFinancingActivities,
    @ChangeInCash,
    @CashAtEndOfPeriod,
    @IncomeTaxesPaid,
    @InterestPaid,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeCashFlowStatements = @"
INSERT INTO public.cash_flow_statements (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    fiscal_period,
    period_end_date,
    depreciation,
    share_based_compensation_expense,
    deferred_income_tax_expense,
    other_non_cash_income_expense,
    change_in_accounts_receivable,
    change_in_inventories,
    change_in_non_trade_receivables,
    change_in_other_assets,
    change_in_accounts_payable,
    change_in_deferred_revenue,
    change_in_other_liabilities,
    cash_from_operating_activities,
    purchases_of_marketable_securities,
    sales_of_marketable_securities,
    acquisition_of_property,
    acquisition_of_business,
    other_investing_activities,
    cash_from_investing_activities,
    tax_withholding_for_share_based_compensation,
    payments_of_dividends,
    issuance_of_common_stock,
    repurchase_of_common_stock,
    issuance_of_long_term_debt,
    repayment_of_long_term_debt,
    other_financing_activities,
    cash_from_financing_activities,
    change_in_cash,
    cash_at_end_of_period,
    income_taxes_paid,
    interest_paid,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @FiscalPeriod,
    @PeriodEndDate,
    @Depreciation,
    @ShareBasedCompensationExpense,
    @DeferredIncomeTaxExpense,
    @OtherNonCashIncomeExpense,
    @ChangeInAccountsReceivable,
    @ChangeInInventories,
    @ChangeInNonTradeReceivables,
    @ChangeInOtherAssets,
    @ChangeInAccountsPayable,
    @ChangeInDeferredRevenue,
    @ChangeInOtherLiabilities,
    @CashFromOperatingActivities,
    @PurchasesOfMarketableSecurities,
    @SalesOfMarketableSecurities,
    @AcquisitionOfProperty,
    @AcquisitionOfBusiness,
    @OtherInvestingActivities,
    @CashFromInvestingActivities,
    @TaxWithholdingForShareBasedCompensation,
    @PaymentsOfDividends,
    @IssuanceOfCommonStock,
    @RepurchaseOfCommonStock,
    @IssuanceOfLongTermDebt,
    @RepaymentOfLongTermDebt,
    @OtherFinancingActivities,
    @CashFromFinancingActivities,
    @ChangeInCash,
    @CashAtEndOfPeriod,
    @IncomeTaxesPaid,
    @InterestPaid,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (central_index_key, fiscal_year, fiscal_period) DO UPDATE SET
    symbol = EXCLUDED.symbol,
    registrant = EXCLUDED.registrant,
    period_end_date = EXCLUDED.period_end_date,
    depreciation = EXCLUDED.depreciation,
    share_based_compensation_expense = EXCLUDED.share_based_compensation_expense,
    deferred_income_tax_expense = EXCLUDED.deferred_income_tax_expense,
    other_non_cash_income_expense = EXCLUDED.other_non_cash_income_expense,
    change_in_accounts_receivable = EXCLUDED.change_in_accounts_receivable,
    change_in_inventories = EXCLUDED.change_in_inventories,
    change_in_non_trade_receivables = EXCLUDED.change_in_non_trade_receivables,
    change_in_other_assets = EXCLUDED.change_in_other_assets,
    change_in_accounts_payable = EXCLUDED.change_in_accounts_payable,
    change_in_deferred_revenue = EXCLUDED.change_in_deferred_revenue,
    change_in_other_liabilities = EXCLUDED.change_in_other_liabilities,
    cash_from_operating_activities = EXCLUDED.cash_from_operating_activities,
    purchases_of_marketable_securities = EXCLUDED.purchases_of_marketable_securities,
    sales_of_marketable_securities = EXCLUDED.sales_of_marketable_securities,
    acquisition_of_property = EXCLUDED.acquisition_of_property,
    acquisition_of_business = EXCLUDED.acquisition_of_business,
    other_investing_activities = EXCLUDED.other_investing_activities,
    cash_from_investing_activities = EXCLUDED.cash_from_investing_activities,
    tax_withholding_for_share_based_compensation = EXCLUDED.tax_withholding_for_share_based_compensation,
    payments_of_dividends = EXCLUDED.payments_of_dividends,
    issuance_of_common_stock = EXCLUDED.issuance_of_common_stock,
    repurchase_of_common_stock = EXCLUDED.repurchase_of_common_stock,
    issuance_of_long_term_debt = EXCLUDED.issuance_of_long_term_debt,
    repayment_of_long_term_debt = EXCLUDED.repayment_of_long_term_debt,
    other_financing_activities = EXCLUDED.other_financing_activities,
    cash_from_financing_activities = EXCLUDED.cash_from_financing_activities,
    change_in_cash = EXCLUDED.change_in_cash,
    cash_at_end_of_period = EXCLUDED.cash_at_end_of_period,
    income_taxes_paid = EXCLUDED.income_taxes_paid,
    interest_paid = EXCLUDED.interest_paid,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectCashFlowStatements = $@"
SELECT
    symbol,
    central_index_key AS CentralIndexKey,
    registrant,
    fiscal_year AS FiscalYear,
    fiscal_period AS FiscalPeriod,
    period_end_date AS PeriodEndDate,
    depreciation AS Depreciation,
    share_based_compensation_expense AS ShareBasedCompensationExpense,
    deferred_income_tax_expense AS DeferredIncomeTaxExpense,
    other_non_cash_income_expense AS OtherNonCashIncomeExpense,
    change_in_accounts_receivable AS ChangeInAccountsReceivable,
    change_in_inventories AS ChangeInInventories,
    change_in_non_trade_receivables AS ChangeInNonTradeReceivables,
    change_in_other_assets AS ChangeInOtherAssets,
    change_in_accounts_payable AS ChangeInAccountsPayable,
    change_in_deferred_revenue AS ChangeInDeferredRevenue,
    change_in_other_liabilities AS ChangeInOtherLiabilities,
    cash_from_operating_activities AS CashFromOperatingActivities,
    purchases_of_marketable_securities AS PurchasesOfMarketableSecurities,
    sales_of_marketable_securities AS SalesOfMarketableSecurities,
    acquisition_of_property AS AcquisitionOfProperty,
    acquisition_of_business AS AcquisitionOfBusiness,
    other_investing_activities AS OtherInvestingActivities,
    cash_from_investing_activities AS CashFromInvestingActivities,
    tax_withholding_for_share_based_compensation AS TaxWithholdingForShareBasedCompensation,
    payments_of_dividends AS PaymentsOfDividends,
    issuance_of_common_stock AS IssuanceOfCommonStock,
    repurchase_of_common_stock AS RepurchaseOfCommonStock,
    issuance_of_long_term_debt AS IssuanceOfLongTermDebt,
    repayment_of_long_term_debt AS RepaymentOfLongTermDebt,
    other_financing_activities AS OtherFinancingActivities,
    cash_from_financing_activities AS CashFromFinancingActivities,
    change_in_cash AS ChangeInCash,
    cash_at_end_of_period AS CashAtEndOfPeriod,
    income_taxes_paid AS IncomeTaxesPaid,
    interest_paid AS InterestPaid,
    {FullAuditSelect}
FROM public.cash_flow_statements";

    
    public const string InsertStockSplits = @"
INSERT INTO public.stock_splits (
    symbol,
    central_index_key,
    registrant,
    execution_date,
    multiplier,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @ExecutionDate,
    @Multiplier,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeStockSplits = @"
INSERT INTO public.stock_splits (
    symbol,
    central_index_key,
    registrant,
    execution_date,
    multiplier,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @ExecutionDate,
    @Multiplier,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (central_index_key, execution_date) DO UPDATE SET
    symbol = EXCLUDED.symbol,
    registrant = EXCLUDED.registrant,
    multiplier = EXCLUDED.multiplier,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectStockSplits = $@"
SELECT
    symbol,
    central_index_key AS CentralIndexKey,
    registrant,
    execution_date AS ExecutionDate,
    multiplier,
    {FullAuditSelect}
FROM public.stock_splits";

    
    public const string InsertDividends = @"
INSERT INTO public.dividends (
    symbol,
    registrant,
    type,
    amount,
    declaration_date,
    ex_date,
    record_date,
    payment_date,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @Registrant,
    @Type,
    @Amount,
    @DeclarationDate,
    @ExDate,
    @RecordDate,
    @PaymentDate,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeDividends = @"
INSERT INTO public.dividends (
    symbol,
    registrant,
    type,
    amount,
    declaration_date,
    ex_date,
    record_date,
    payment_date,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @Registrant,
    @Type,
    @Amount,
    @DeclarationDate,
    @ExDate,
    @RecordDate,
    @PaymentDate,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (symbol, record_date) DO UPDATE SET
    registrant = EXCLUDED.registrant,
    type = EXCLUDED.type,
    amount = EXCLUDED.amount,
    declaration_date = EXCLUDED.declaration_date,
    payment_date = EXCLUDED.payment_date,
    ex_date = EXCLUDED.ex_date,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectDividends = $@"
SELECT
    symbol,
    registrant,
    type AS Type,
    amount AS Amount,
    declaration_date AS DeclarationDate,
    ex_date AS ExDate,
    record_date AS RecordDate,
    payment_date AS PaymentDate,
    {FullAuditSelect}
FROM public.dividends";

    
    public const string InsertEarningsReleases = @"
INSERT INTO public.earnings_releases (
    symbol,
    central_index_key,
    registrant_name,
    market_cap,
    fiscal_quarter_end_date,
    earnings_per_share,
    earnings_per_share_forecast,
    percentage_surprise,
    number_of_forecasts,
    conference_call_time,
    conference_call_unix_ms,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @RegistrantName,
    @MarketCap,
    @FiscalQuarterEndDate,
    @EarningsPerShare,
    @EarningsPerShareForecast,
    @PercentageSurprise,
    @NumberOfForecasts,
    @ConferenceCallTime,
    @ConferenceCallUnixMs,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeEarningsReleases = @"
INSERT INTO public.earnings_releases (
    symbol,
    central_index_key,
    registrant_name,
    market_cap,
    fiscal_quarter_end_date,
    earnings_per_share,
    earnings_per_share_forecast,
    percentage_surprise,
    number_of_forecasts,
    conference_call_time,
    conference_call_unix_ms,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @RegistrantName,
    @MarketCap,
    @FiscalQuarterEndDate,
    @EarningsPerShare,
    @EarningsPerShareForecast,
    @PercentageSurprise,
    @NumberOfForecasts,
    @ConferenceCallTime,
    @ConferenceCallUnixMs,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (central_index_key, fiscal_quarter_end_date) DO UPDATE SET
    symbol = EXCLUDED.symbol,
    registrant_name = EXCLUDED.registrant_name,
    market_cap = EXCLUDED.market_cap,
    earnings_per_share = EXCLUDED.earnings_per_share,
    earnings_per_share_forecast = EXCLUDED.earnings_per_share_forecast,
    percentage_surprise = EXCLUDED.percentage_surprise,
    number_of_forecasts = EXCLUDED.number_of_forecasts,
    conference_call_time = EXCLUDED.conference_call_time,
    conference_call_unix_ms = EXCLUDED.conference_call_unix_ms,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectEarningsReleases = $@"
SELECT
    symbol AS Symbol,
    central_index_key AS CentralIndexKey,
    registrant_name AS RegistrantName,
    market_cap AS MarketCap,
    fiscal_quarter_end_date AS FiscalQuarterEndDate,
    earnings_per_share AS EarningsPerShare,
    earnings_per_share_forecast AS EarningsPerShareForecast,
    percentage_surprise AS PercentageSurprise,
    number_of_forecasts AS NumberOfForecasts,
    conference_call_time AS ConferenceCallTime,
    conference_call_unix_ms AS ConferenceCallUnixMs,
    {FullAuditSelect}
FROM public.earnings_releases";

    
    public const string InsertEfficiencyRatios = @"
INSERT INTO public.efficiency_ratios (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    fiscal_period,
    period_end_date,
    asset_turnover_ratio,
    inventory_turnover_ratio,
    accounts_receivable_turnover_ratio,
    accounts_payable_turnover_ratio,
    equity_multiplier,
    days_sales_in_inventory,
    fixed_asset_turnover_ratio,
    days_working_capital,
    working_capital_turnover_ratio,
    days_cash_on_hand,
    capital_intensity_ratio,
    sales_to_equity_ratio,
    inventory_to_sales_ratio,
    investment_turnover_ratio,
    sales_to_operating_income_ratio,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @FiscalPeriod,
    @PeriodEndDate,
    @AssetTurnoverRatio,
    @InventoryTurnoverRatio,
    @AccountsReceivableTurnoverRatio,
    @AccountsPayableTurnoverRatio,
    @EquityMultiplier,
    @DaysSalesInInventory,
    @FixedAssetTurnoverRatio,
    @DaysWorkingCapital,
    @WorkingCapitalTurnoverRatio,
    @DaysCashOnHand,
    @CapitalIntensityRatio,
    @SalesToEquityRatio,
    @InventoryToSalesRatio,
    @InvestmentTurnoverRatio,
    @SalesToOperatingIncomeRatio,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeEfficiencyRatios = @"
INSERT INTO public.efficiency_ratios (
    symbol,
    central_index_key,
    registrant,
    fiscal_year,
    fiscal_period,
    period_end_date,
    asset_turnover_ratio,
    inventory_turnover_ratio,
    accounts_receivable_turnover_ratio,
    accounts_payable_turnover_ratio,
    equity_multiplier,
    days_sales_in_inventory,
    fixed_asset_turnover_ratio,
    days_working_capital,
    working_capital_turnover_ratio,
    days_cash_on_hand,
    capital_intensity_ratio,
    sales_to_equity_ratio,
    inventory_to_sales_ratio,
    investment_turnover_ratio,
    sales_to_operating_income_ratio,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @CentralIndexKey,
    @Registrant,
    @FiscalYear,
    @FiscalPeriod,
    @PeriodEndDate,
    @AssetTurnoverRatio,
    @InventoryTurnoverRatio,
    @AccountsReceivableTurnoverRatio,
    @AccountsPayableTurnoverRatio,
    @EquityMultiplier,
    @DaysSalesInInventory,
    @FixedAssetTurnoverRatio,
    @DaysWorkingCapital,
    @WorkingCapitalTurnoverRatio,
    @DaysCashOnHand,
    @CapitalIntensityRatio,
    @SalesToEquityRatio,
    @InventoryToSalesRatio,
    @InvestmentTurnoverRatio,
    @SalesToOperatingIncomeRatio,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (central_index_key, fiscal_year, fiscal_period) DO UPDATE SET
    symbol = EXCLUDED.symbol,
    registrant = EXCLUDED.registrant,
    period_end_date = EXCLUDED.period_end_date,
    asset_turnover_ratio = EXCLUDED.asset_turnover_ratio,
    inventory_turnover_ratio = EXCLUDED.inventory_turnover_ratio,
    accounts_receivable_turnover_ratio = EXCLUDED.accounts_receivable_turnover_ratio,
    accounts_payable_turnover_ratio = EXCLUDED.accounts_payable_turnover_ratio,
    equity_multiplier = EXCLUDED.equity_multiplier,
    days_sales_in_inventory = EXCLUDED.days_sales_in_inventory,
    fixed_asset_turnover_ratio = EXCLUDED.fixed_asset_turnover_ratio,
    days_working_capital = EXCLUDED.days_working_capital,
    working_capital_turnover_ratio = EXCLUDED.working_capital_turnover_ratio,
    days_cash_on_hand = EXCLUDED.days_cash_on_hand,
    capital_intensity_ratio = EXCLUDED.capital_intensity_ratio,
    sales_to_equity_ratio = EXCLUDED.sales_to_equity_ratio,
    inventory_to_sales_ratio = EXCLUDED.inventory_to_sales_ratio,
    investment_turnover_ratio = EXCLUDED.investment_turnover_ratio,
    sales_to_operating_income_ratio = EXCLUDED.sales_to_operating_income_ratio,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectEfficiencyRatios = $@"
SELECT
    symbol,
    central_index_key AS CentralIndexKey,
    registrant,
    fiscal_year AS FiscalYear,
    fiscal_period AS FiscalPeriod,
    period_end_date AS PeriodEndDate,
    asset_turnover_ratio AS AssetTurnoverRatio,
    inventory_turnover_ratio AS InventoryTurnoverRatio,
    accounts_receivable_turnover_ratio AS AccountsReceivableTurnoverRatio,
    accounts_payable_turnover_ratio AS AccountsPayableTurnoverRatio,
    equity_multiplier AS EquityMultiplier,
    days_sales_in_inventory AS DaysSalesInInventory,
    fixed_asset_turnover_ratio AS FixedAssetTurnoverRatio,
    days_working_capital AS DaysWorkingCapital,
    working_capital_turnover_ratio AS WorkingCapitalTurnoverRatio,
    days_cash_on_hand AS DaysCashOnHand,
    capital_intensity_ratio AS CapitalIntensityRatio,
    sales_to_equity_ratio AS SalesToEquityRatio,
    inventory_to_sales_ratio AS InventoryToSalesRatio,
    investment_turnover_ratio AS InvestmentTurnoverRatio,
    sales_to_operating_income_ratio AS SalesToOperatingIncomeRatio,
    {FullAuditSelect}
FROM public.efficiency_ratios";

    
    public const string InsertShortInterests = @"
INSERT INTO public.short_interests (
    symbol,
    title,
    market_code,
    settlement_date,
    shorted_securities,
    previous_shorted_securities,
    change_in_shorted_securities,
    percentage_change_in_shorted_securities,
    average_daily_volume,
    days_to_cover,
    is_stock_split,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @Title,
    @MarketCode,
    @SettlementDate,
    @ShortedSecurities,
    @PreviousShortedSecurities,
    @ChangeInShortedSecurities,
    @PercentageChangeInShortedSecurities,
    @AverageDailyVolume,
    @DaysToCover,
    @IsStockSplit,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeShortInterests = @"
INSERT INTO public.short_interests (
    symbol,
    title,
    market_code,
    settlement_date,
    shorted_securities,
    previous_shorted_securities,
    change_in_shorted_securities,
    percentage_change_in_shorted_securities,
    average_daily_volume,
    days_to_cover,
    is_stock_split,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (
    @Symbol,
    @Title,
    @MarketCode,
    @SettlementDate,
    @ShortedSecurities,
    @PreviousShortedSecurities,
    @ChangeInShortedSecurities,
    @PercentageChangeInShortedSecurities,
    @AverageDailyVolume,
    @DaysToCover,
    @IsStockSplit,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (symbol, settlement_date) DO UPDATE SET
    title = EXCLUDED.title,
    market_code = EXCLUDED.market_code,
    shorted_securities = EXCLUDED.shorted_securities,
    previous_shorted_securities = EXCLUDED.previous_shorted_securities,
    change_in_shorted_securities = EXCLUDED.change_in_shorted_securities,
    percentage_change_in_shorted_securities = EXCLUDED.percentage_change_in_shorted_securities,
    average_daily_volume = EXCLUDED.average_daily_volume,
    days_to_cover = EXCLUDED.days_to_cover,
    is_stock_split = EXCLUDED.is_stock_split,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectShortInterests = $@"
SELECT
    symbol,
    title,
    market_code AS MarketCode,
    settlement_date AS SettlementDate,
    shorted_securities AS ShortedSecurities,
    previous_shorted_securities AS PreviousShortedSecurities,
    change_in_shorted_securities AS ChangeInShortedSecurities,
    percentage_change_in_shorted_securities AS PercentageChangeInShortedSecurities,
    average_daily_volume AS AverageDailyVolume,
    days_to_cover AS DaysToCover,
    is_stock_split AS IsStockSplit,
    {FullAuditSelect}
FROM public.short_interests";

    
    public const string InsertProcess = @"
INSERT INTO public.processes(
    process_id,
    process_type,
    start_time,
    finish_time,
    start_time_unix_ms,
    finish_time_unix_ms,
    input_path,
    output_path,
    parent_process_id,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES(
    @ProcessId,
    @ProcessType,
    @StartTime,
    @FinishTime,
    @StartTimeUnixMs,
    @FinishTimeUnixMs,
    @InputPath,
    @OutputPath,
    @ParentProcessId,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeProcess = @"
INSERT INTO public.processes(
    process_id,
    process_type,
    start_time,
    finish_time,
    start_time_unix_ms,
    finish_time_unix_ms,
    input_path,
    output_path,
    parent_process_id,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES(
    @ProcessId,
    @ProcessType,
    @StartTime,
    @FinishTime,
    @StartTimeUnixMs,
    @FinishTimeUnixMs,
    @InputPath,
    @OutputPath,
    @ParentProcessId,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
) ON CONFLICT (process_id) DO UPDATE SET
    finish_time = EXCLUDED.finish_time,
    finish_time_unix_ms = EXCLUDED.finish_time_unix_ms,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";

    public const string SelectProcess = $@"
SELECT
    process_id AS ProcessId,
    process_type AS ProcessType,
    start_time_unix_ms AS StartTimeUnixMs,
    finish_time_unix_ms AS FinishTimeUnixMs,
    input_path AS InputPath,
    output_path AS OutputPath,
    parent_process_id AS ParentProcessId,
    {FullAuditSelect}
FROM public.processes";

 
    public const string InsertIgnoredSymbol = @"
INSERT INTO public.ignored_symbols(
    symbol,
    reason,
    expiration,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms)
VALUES(
    @Symbol,
    @Reason,
    @Expiration,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs
)";

    public const string MergeIgnoredSymbol = @"
INSERT INTO public.ignored_symbols(
    symbol,
    reason,
    expiration,
    created_by,
    updated_by,
    created_at,
    updated_at,
    created_at_unix_ms,
    updated_at_unix_ms)
VALUES(
    @Symbol,
    @Reason,
    @Expiration,
    @CreatedBy,
    @UpdatedBy,
    @CreatedAt,
    @UpdatedAt,
    @CreatedAtUnixMs,
    @UpdatedAtUnixMs)
ON CONFLICT (symbol) DO UPDATE SET
    reason = EXCLUDED.reason,
    expiration = EXCLUDED.expiration,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    updated_at_unix_ms = EXCLUDED.updated_at_unix_ms";
    
    public const string SelectIgnoredSymbol = $@"
SELECT
    symbol,
    reason,
    expiration,
    {FullAuditSelect}
FROM public.ignored_symbols";
}