CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS public.securities CASCADE;
DROP TABLE IF EXISTS public.eod_prices CASCADE;
DROP TABLE IF EXISTS public.us_companies CASCADE;
DROP TABLE IF EXISTS public.international_companies CASCADE;
DROP TABLE IF EXISTS public.security_information CASCADE;
DROP TABLE IF EXISTS public.liquidity_ratios CASCADE;
DROP TABLE IF EXISTS public.profitability_ratios CASCADE;
DROP TABLE IF EXISTS public.solvency_ratios CASCADE;
DROP TABLE IF EXISTS public.valuation_ratios CASCADE;
DROP TABLE IF EXISTS public.key_metrics CASCADE;
DROP TABLE IF EXISTS public.market_caps CASCADE;
DROP TABLE IF EXISTS public.employee_counts CASCADE;
DROP TABLE IF EXISTS public.executive_compensations CASCADE;
DROP TABLE IF EXISTS public.income_statements CASCADE;
DROP TABLE IF EXISTS public.balance_sheets CASCADE;
DROP TABLE IF EXISTS public.cash_flow_statements CASCADE;
DROP TABLE IF EXISTS public.stock_splits CASCADE;
DROP TABLE IF EXISTS public.dividends CASCADE;
DROP TABLE IF EXISTS public.earnings_releases CASCADE;
DROP TABLE IF EXISTS public.efficiency_ratios CASCADE;
DROP TABLE IF EXISTS public.short_interests CASCADE;

-- This table represents all different types of securities,
-- such as stocks, ETFs, crypto, etc.
CREATE TABLE IF NOT EXISTS public.securities (
    symbol TEXT NOT NULL,
    security_type TEXT NOT NULL,
    registrant TEXT,
    description TEXT,
    sub_type TEXT,
    base_asset TEXT,
    quote_asset TEXT,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (symbol, security_type)
);

CREATE TABLE IF NOT EXISTS public.security_information (
    symbol TEXT NOT NULL,
    issuer TEXT NOT NULL,
    cusip TEXT,
    isin TEXT,
    figi TEXT,
    type TEXT NOT NULL,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (symbol)
);

CREATE TABLE IF NOT EXISTS public.eod_prices (
    symbol TEXT NOT NULL,
    security_type TEXT NOT NULL,
    date_eod DATE NOT NULL,
    open NUMERIC(22,4) NOT NULL,
    high NUMERIC(22,4) NOT NULL,
    low NUMERIC(22,4) NOT NULL,
    close NUMERIC(22,4) NOT NULL,
    volume DOUBLE PRECISION NOT NULL,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (symbol, security_type, date_eod)
);

CREATE TABLE IF NOT EXISTS public.us_companies (
    central_index_key TEXT NOT NULL,
    exchange TEXT NOT NULL,
    symbol TEXT NOT NULL,
    registrant TEXT NOT NULL,
    isin TEXT,
    lei TEXT,
    ein TEXT,
    sic_code TEXT,
    sic_description TEXT,
    fiscal_year_end TEXT,
    state_of_incorporation TEXT,
    phone_number TEXT,
    mailing_address TEXT,
    business_address TEXT,
    former_name TEXT,
    industry TEXT,
    date_founding DATE,
    chief_executive_officer TEXT,
    number_employees INTEGER,
    web_site TEXT,
    market_cap DOUBLE PRECISION,
    shares_issued DOUBLE PRECISION,
    shares_outstanding DOUBLE PRECISION,
    description TEXT,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (central_index_key, exchange, symbol)
);

CREATE TABLE IF NOT EXISTS public.international_companies (
    symbol TEXT NOT NULL,
    registrant TEXT NOT NULL,
    exchange TEXT NOT NULL,
    isin TEXT,
    industry TEXT NOT NULL,
    year_founding TEXT NOT NULL,
    chief_executive_officer TEXT NOT NULL,
    number_employees INTEGER,
    web_site TEXT NOT NULL,
    description TEXT NOT NULL,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (symbol, exchange)
);

CREATE TABLE IF NOT EXISTS public.liquidity_ratios (
    symbol TEXT NOT NULL,
    central_index_key TEXT NOT NULL,
    registrant TEXT NOT NULL,
    fiscal_year TEXT NOT NULL,
    fiscal_period TEXT NOT NULL,
    period_end_date DATE NOT NULL,
    working_capital NUMERIC(22,4) NOT NULL,
    current_ratio DOUBLE PRECISION NOT NULL,
    cash_ratio DOUBLE PRECISION NOT NULL,
    quick_ratio DOUBLE PRECISION NOT NULL,
    days_of_inventory_outstanding DOUBLE PRECISION NOT NULL,
    days_of_sales_outstanding DOUBLE PRECISION NOT NULL,
    days_payable_outstanding DOUBLE PRECISION NOT NULL,
    cash_conversion_cycle DOUBLE PRECISION NOT NULL,
    sales_to_working_capital_ratio DOUBLE PRECISION NOT NULL,
    cash_to_current_liabilities_ratio DOUBLE PRECISION NOT NULL,
    working_capital_to_debt_ratio DOUBLE PRECISION NOT NULL,
    cash_flow_adequacy_ratio DOUBLE PRECISION NOT NULL,
    sales_to_current_assets_ratio DOUBLE PRECISION NOT NULL,
    cash_to_current_assets_ratio DOUBLE PRECISION NOT NULL,
    cash_to_working_capital_ratio DOUBLE PRECISION NOT NULL,
    inventory_to_working_capital_ratio DOUBLE PRECISION NOT NULL,
    net_debt NUMERIC(22,4) NOT NULL,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (central_index_key, fiscal_year, fiscal_period)
);

CREATE TABLE IF NOT EXISTS public.profitability_ratios (
    symbol TEXT NOT NULL,
    central_index_key TEXT NOT NULL,
    registrant TEXT NOT NULL,
    fiscal_year TEXT NOT NULL,
    fiscal_period TEXT NOT NULL,
    period_end_date DATE NOT NULL,
    ebit NUMERIC(22,4) NOT NULL,
    ebitda NUMERIC(22,4) NOT NULL,
    profit_margin DOUBLE PRECISION NOT NULL,
    gross_margin DOUBLE PRECISION NOT NULL,
    operating_margin DOUBLE PRECISION NOT NULL,
    operating_cash_flow_margin DOUBLE PRECISION NOT NULL,
    return_on_equity DOUBLE PRECISION NOT NULL,
    return_on_assets DOUBLE PRECISION NOT NULL,
    return_on_debt DOUBLE PRECISION NOT NULL,
    cash_return_on_assets DOUBLE PRECISION NOT NULL,
    cash_turnover_ratio DOUBLE PRECISION NOT NULL,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (central_index_key, fiscal_year, fiscal_period)
);

CREATE TABLE IF NOT EXISTS public.solvency_ratios (
    symbol TEXT NOT NULL,
    central_index_key TEXT NOT NULL,
    registrant TEXT NOT NULL,
    fiscal_year TEXT NOT NULL,
    fiscal_period TEXT NOT NULL,
    period_end_date DATE NOT NULL,
    equity_ratio DOUBLE PRECISION NOT NULL,
    debt_coverage_ratio DOUBLE PRECISION,
    asset_coverage_ratio DOUBLE PRECISION NOT NULL,
    interest_coverage_ratio DOUBLE PRECISION,
    debt_to_equity_ratio DOUBLE PRECISION NOT NULL,
    debt_to_assets_ratio DOUBLE PRECISION NOT NULL,
    debt_to_capital_ratio DOUBLE PRECISION NOT NULL,
    debt_to_income_ratio DOUBLE PRECISION,
    cash_flow_to_debt_ratio DOUBLE PRECISION NOT NULL,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (central_index_key, fiscal_year, fiscal_period)
);

CREATE TABLE IF NOT EXISTS public.valuation_ratios (
    symbol TEXT NOT NULL,
    central_index_key TEXT NOT NULL,
    registrant TEXT NOT NULL,
    fiscal_year TEXT NOT NULL,
    fiscal_period TEXT NOT NULL,
    period_end_date DATE NOT NULL,
    dividends_per_share NUMERIC(22,4) NOT NULL,
    dividend_payout_ratio DOUBLE PRECISION NOT NULL,
    book_value_per_share NUMERIC(22,4) NOT NULL,
    retention_ratio DOUBLE PRECISION NOT NULL,
    net_fixed_assets NUMERIC(22,4) NOT NULL,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (central_index_key, fiscal_year, fiscal_period)
);

CREATE TABLE IF NOT EXISTS public.key_metrics (
    symbol TEXT NOT NULL,
    central_index_key TEXT NOT NULL,
    registrant TEXT NOT NULL,
    fiscal_year TEXT NOT NULL,
    period_end_date DATE NOT NULL,
    earnings_per_share NUMERIC(22,4) NOT NULL,
    earnings_per_share_forecast NUMERIC(22,4) NOT NULL,
    price_to_earnings_ratio DOUBLE PRECISION NOT NULL,
    forward_price_to_earnings_ratio DOUBLE PRECISION NOT NULL,
    earnings_growth_rate DOUBLE PRECISION NOT NULL,
    price_earnings_to_growth_rate DOUBLE PRECISION NOT NULL,
    book_value_per_share NUMERIC(22,4) NOT NULL,
    price_to_book_ratio DOUBLE PRECISION NOT NULL,
    ebitda DOUBLE PRECISION NOT NULL,
    enterprise_value NUMERIC(22,4) NOT NULL,
    dividend_yield DOUBLE PRECISION NOT NULL,
    dividend_payout_ratio DOUBLE PRECISION NOT NULL,
    debt_to_equity_ratio DOUBLE PRECISION NOT NULL,
    capital_expenditures NUMERIC(22,4) NOT NULL,
    free_cash_flow NUMERIC(22,4) NOT NULL,
    return_on_equity NUMERIC(22,4) NOT NULL,
    one_year_beta DOUBLE PRECISION NOT NULL,
    three_year_beta DOUBLE PRECISION NOT NULL,
    five_year_beta DOUBLE PRECISION NOT NULL,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (central_index_key, fiscal_year)
);

CREATE TABLE IF NOT EXISTS public.market_caps (
    symbol TEXT NOT NULL,
    central_index_key TEXT NOT NULL,
    registrant TEXT NOT NULL,
    fiscal_year TEXT NOT NULL,
    value NUMERIC(22,4) NOT NULL,
    change_in_market_cap NUMERIC(22,4) NOT NULL,
    percentage_change_in_market_cap DOUBLE PRECISION NOT NULL,
    shares_outstanding BIGINT NOT NULL,
    change_in_shares_outstanding BIGINT NOT NULL,
    percentage_change_in_shares_outstanding DOUBLE PRECISION NOT NULL,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (central_index_key, fiscal_year)
);

CREATE TABLE IF NOT EXISTS public.employee_counts (
    symbol TEXT NOT NULL,
    central_index_key TEXT NOT NULL,
    registrant TEXT NOT NULL,
    fiscal_year TEXT NOT NULL,
    count INTEGER NOT NULL,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (central_index_key, fiscal_year)
);

CREATE TABLE IF NOT EXISTS public.executive_compensations (
    symbol TEXT NOT NULL,
    central_index_key TEXT NOT NULL,
    registrant TEXT NOT NULL,
    name TEXT NOT NULL,
    position TEXT NOT NULL,
    fiscal_year TEXT NOT NULL,
    salary NUMERIC(22,4) NOT NULL,
    bonus NUMERIC(22,4) NOT NULL,
    stock_awards NUMERIC(22,4) NOT NULL,
    incentive_plan_compensation NUMERIC(22,4) NOT NULL,
    other_compensation NUMERIC(22,4) NOT NULL,
    total_compensation NUMERIC(22,4) NOT NULL,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (central_index_key, name, position, fiscal_year)
);

CREATE TABLE IF NOT EXISTS public.income_statements (
    symbol TEXT NOT NULL,
    central_index_key TEXT NOT NULL,
    registrant TEXT NOT NULL,
    fiscal_year TEXT NOT NULL,
    fiscal_period TEXT NOT NULL,
    period_end_date DATE NOT NULL,
    revenue NUMERIC(22,4) NOT NULL,
    cost_of_revenue NUMERIC(22,4) NOT NULL,
    gross_profit NUMERIC(22,4) NOT NULL,
    research_development_expenses NUMERIC(22,4) NOT NULL,
    general_admin_expenses NUMERIC(22,4) NOT NULL,
    operating_expenses NUMERIC(22,4) NOT NULL,
    operating_income NUMERIC(22,4) NOT NULL,
    interest_expense NUMERIC(22,4) NOT NULL,
    interest_income NUMERIC(22,4) NOT NULL,
    net_income NUMERIC(22,4) NOT NULL,
    earnings_per_share_basic NUMERIC(22,4) NOT NULL,
    earnings_per_share_diluted NUMERIC(22,4) NOT NULL,
    weighted_average_shares_outstanding_basic BIGINT NOT NULL,
    weighted_average_shares_outstanding_diluted BIGINT NOT NULL,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (central_index_key, fiscal_year, fiscal_period)
);

CREATE TABLE IF NOT EXISTS public.balance_sheets (
    symbol TEXT NOT NULL,
    central_index_key TEXT NOT NULL,
    registrant TEXT NOT NULL,
    fiscal_year TEXT NOT NULL,
    fiscal_period TEXT NOT NULL,
    period_end_date DATE NOT NULL,
    cash NUMERIC(22,4) NOT NULL,
    marketable_securities_current NUMERIC(22,4) NOT NULL,
    accounts_receivable NUMERIC(22,4) NOT NULL,
    inventories NUMERIC(22,4) NOT NULL,
    non_trade_receivables NUMERIC(22,4) NOT NULL,
    other_assets_current NUMERIC(22,4) NOT NULL,
    total_assets_current NUMERIC(22,4) NOT NULL,
    marketable_securities_non_current NUMERIC(22,4) NOT NULL,
    property_plant_equipment NUMERIC(22,4) NOT NULL,
    other_assets_non_current NUMERIC(22,4) NOT NULL,
    total_assets_non_current NUMERIC(22,4) NOT NULL,
    total_assets NUMERIC(22,4) NOT NULL,
    accounts_payable NUMERIC(22,4) NOT NULL,
    deferred_revenue NUMERIC(22,4) NOT NULL,
    short_term_debt NUMERIC(22,4) NOT NULL,
    other_liabilities_current NUMERIC(22,4) NOT NULL,
    total_liabilities_current NUMERIC(22,4) NOT NULL,
    long_term_debt NUMERIC(22,4) NOT NULL,
    other_liabilities_non_current NUMERIC(22,4) NOT NULL,
    total_liabilities_non_current NUMERIC(22,4) NOT NULL,
    total_liabilities NUMERIC(22,4) NOT NULL,
    common_stock NUMERIC(22,4) NOT NULL,
    retained_earnings NUMERIC(22,4) NOT NULL,
    accumulated_other_comprehensive_income NUMERIC(22,4) NOT NULL,
    total_shareholders_equity NUMERIC(22,4) NOT NULL,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (central_index_key, fiscal_year, fiscal_period)
);

CREATE TABLE IF NOT EXISTS public.cash_flow_statements (
    symbol TEXT NOT NULL,
    central_index_key TEXT NOT NULL,
    registrant TEXT NOT NULL,
    fiscal_year TEXT NOT NULL,
    fiscal_period TEXT NOT NULL,
    period_end_date DATE NOT NULL,
    depreciation NUMERIC(22,4) NOT NULL,
    share_based_compensation_expense NUMERIC(22,4) NOT NULL,
    deferred_income_tax_expense NUMERIC(22,4) NOT NULL,
    other_non_cash_income_expense NUMERIC(22,4) NOT NULL,
    change_in_accounts_receivable NUMERIC(22,4) NOT NULL,
    change_in_inventories NUMERIC(22,4) NOT NULL,
    change_in_non_trade_receivables NUMERIC(22,4) NOT NULL,
    change_in_other_assets NUMERIC(22,4) NOT NULL,
    change_in_accounts_payable NUMERIC(22,4) NOT NULL,
    change_in_deferred_revenue NUMERIC(22,4) NOT NULL,
    change_in_other_liabilities NUMERIC(22,4) NOT NULL,
    cash_from_operating_activities NUMERIC(22,4) NOT NULL,
    purchases_of_marketable_securities NUMERIC(22,4) NOT NULL,
    sales_of_marketable_securities NUMERIC(22,4) NOT NULL,
    acquisition_of_property NUMERIC(22,4) NOT NULL,
    acquisition_of_business NUMERIC(22,4) NOT NULL,
    other_investing_activities NUMERIC(22,4) NOT NULL,
    cash_from_investing_activities NUMERIC(22,4) NOT NULL,
    tax_withholding_for_share_based_compensation NUMERIC(22,4) NOT NULL,
    payments_of_dividends NUMERIC(22,4) NOT NULL,
    issuance_of_common_stock NUMERIC(22,4) NOT NULL,
    repurchase_of_common_stock NUMERIC(22,4) NOT NULL,
    issuance_of_long_term_debt NUMERIC(22,4) NOT NULL,
    repayment_of_long_term_debt NUMERIC(22,4) NOT NULL,
    other_financing_activities NUMERIC(22,4) NOT NULL,
    cash_from_financing_activities NUMERIC(22,4) NOT NULL,
    change_in_cash NUMERIC(22,4) NOT NULL,
    cash_at_end_of_period NUMERIC(22,4) NOT NULL,
    income_taxes_paid NUMERIC(22,4) NOT NULL,
    interest_paid NUMERIC(22,4) NOT NULL,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (central_index_key, fiscal_year, fiscal_period)
);

CREATE TABLE IF NOT EXISTS public.stock_splits (
    symbol TEXT NOT NULL,
    central_index_key TEXT NOT NULL,
    registrant TEXT NOT NULL,
    execution_date DATE NOT NULL,
    multiplier DOUBLE PRECISION NOT NULL,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (central_index_key, execution_date)
);

CREATE TABLE IF NOT EXISTS public.dividends (
    symbol TEXT NOT NULL,
    registrant TEXT NOT NULL,
    type TEXT NOT NULL,
    amount NUMERIC(22,4) NOT NULL,
    declaration_date DATE NOT NULL,
    ex_date DATE NOT NULL,
    record_date DATE NOT NULL,
    payment_date DATE NOT NULL,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (symbol, ex_date)
);

CREATE TABLE IF NOT EXISTS public.earnings_releases (
    trading_symbol TEXT NOT NULL,
    central_index_key TEXT NOT NULL,
    registrant_name TEXT NOT NULL,
    market_cap NUMERIC(22,4) NOT NULL,
    fiscal_quarter_end_date TEXT NOT NULL,
    earnings_per_share NUMERIC(22,4) NOT NULL,
    earnings_per_share_forecast NUMERIC(22,4) NOT NULL,
    percentage_surprise DOUBLE PRECISION NOT NULL,
    number_of_forecasts INTEGER NOT NULL,
    conference_call_time TIMESTAMPTZ NOT NULL,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (central_index_key, fiscal_quarter_end_date)
);

CREATE TABLE IF NOT EXISTS public.efficiency_ratios (
    symbol TEXT NOT NULL,
    central_index_key TEXT NOT NULL,
    registrant TEXT NOT NULL,
    fiscal_year TEXT NOT NULL,
    fiscal_period TEXT NOT NULL,
    period_end_date DATE NOT NULL,
    asset_turnover_ratio DOUBLE PRECISION NOT NULL,
    inventory_turnover_ratio DOUBLE PRECISION NOT NULL,
    accounts_receivable_turnover_ratio DOUBLE PRECISION NOT NULL,
    accounts_payable_turnover_ratio DOUBLE PRECISION NOT NULL,
    equity_multiplier DOUBLE PRECISION NOT NULL,
    days_sales_in_inventory DOUBLE PRECISION NOT NULL,
    fixed_asset_turnover_ratio DOUBLE PRECISION NOT NULL,
    days_working_capital DOUBLE PRECISION NOT NULL,
    working_capital_turnover_ratio DOUBLE PRECISION NOT NULL,
    days_cash_on_hand DOUBLE PRECISION,
    capital_intensity_ratio DOUBLE PRECISION NOT NULL,
    sales_to_equity_ratio DOUBLE PRECISION NOT NULL,
    inventory_to_sales_ratio DOUBLE PRECISION NOT NULL,
    investment_turnover_ratio DOUBLE PRECISION NOT NULL,
    sales_to_operating_income_ratio DOUBLE PRECISION NOT NULL,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (central_index_key, fiscal_year, fiscal_period)
);

CREATE TABLE IF NOT EXISTS public.short_interests (
    symbol TEXT NOT NULL,
    title TEXT NOT NULL,
    market_code TEXT NOT NULL,
    settlement_date DATE NOT NULL,
    shorted_securities BIGINT NOT NULL,
    previous_shorted_securities BIGINT NOT NULL,
    change_in_shorted_securities BIGINT NOT NULL,
    percentage_change_in_shorted_securities DOUBLE PRECISION NOT NULL,
    average_daily_volume BIGINT NOT NULL,
    days_to_convert DOUBLE PRECISION NOT NULL,
    is_stock_split BOOLEAN NOT NULL,
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at_unix_ms BIGINT NOT NULL,
    updated_at_unix_ms BIGINT NOT NULL,
    PRIMARY KEY (symbol, settlement_date)
);